# Generated by Django 3.2.8 on 2021-10-31 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionsanswers', '0003_auto_20211030_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='questionsanswers.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionsanswers.question', verbose_name='Next question id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_answer',
            field=models.IntegerField(choices=[(1, 'radio'), (2, 'checkbox'), (3, 'input'), (4, 'counter')], max_length=20, verbose_name='Type Answer'),
        ),
    ]
