# Generated by Django 3.2.8 on 2021-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsanswers', '0005_auto_20211123_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='enum',
            field=models.TextField(max_length=255, unique=True, verbose_name='Unique str identifier'),
        ),
        migrations.AlterField(
            model_name='question',
            name='enum',
            field=models.TextField(max_length=255, unique=True, verbose_name='Unique str identifier'),
        ),
    ]
