# Generated by Django 3.2.8 on 2021-12-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsanswers', '0007_alter_question_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_answer',
            field=models.IntegerField(choices=[(1, 'radio'), (2, 'checkbox'), (3, 'input'), (4, 'counter')], verbose_name='Type Answer'),
        ),
    ]
