version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./test-data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8085:8080"
    environment:
      - CARBO_DEBUG=True
    depends_on:
      - db
    # TODO: python manage.py migrate