"""
Django settings for Carbo project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

env = environ.Env(
    # Set casting and default values
    CARBO_SITE_URL=(str, 'http://localhost:8080'),
    CARBO_DEBUG=(bool, False),
    CARBO_SECRET_KEY=(str, '**xsp0frzg2wz5b&t234=4wf424z*t_#+baegdfgd!5n6wa(!p(r'),
    CARBO_DATABASE_ENGINE=(str, 'django.db.backends.postgresql'),
    CARBO_DATABASE_HOST=(str, 'db'),
    CARBO_DATABASE_PORT=(int, 5432),
    CARBO_DATABASE_NAME=(str, 'postgres'),
    CARBO_DATABASE_USER=(str, 'postgres'),
    CARBO_DATABASE_PASSWORD=(str, 'postgres'),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('CARBO_DEBUG')
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('CARBO_SECRET_KEY')

ALLOWED_HOSTS = tuple(env.list('CARBO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1']))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'questionsanswers'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Carbo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Carbo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('CARBO_DATABASE_ENGINE'),
        'NAME': env('CARBO_DATABASE_NAME'),
        'USER': env('CARBO_DATABASE_USER'),
        'PASSWORD': env('CARBO_DATABASE_PASSWORD'),
        'HOST': env('CARBO_DATABASE_HOST'),
        'PORT': env('CARBO_DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'